In [2]:
import sys
import os
sys.path.append('../..')
import datasets

/home/holywater2/.conda/envs/infGCN/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
density_dataset = datasets.DensityDataset

In [6]:
root = "../../../dataset_pbc/datas_filtered"
split_file = "cubic_data_split.json"
split = "train"
atom_file = "../../atom_info/crystal.json"
extension = "json"
compression = "xz"

In [7]:
train = density_dataset(root=root, split_file=split_file, split="train", atom_file=atom_file, extension=extension, compression=compression)

In [12]:
tt = train[0]

In [13]:
import torch

In [19]:
c = tt[3]["cell"]

In [22]:
c[0]

tensor([9.0198, 0.0000, 0.0000])

In [25]:
bins = torch.linspace(0, 1, 4)

In [26]:
bins

tensor([0.0000, 0.3333, 0.6667, 1.0000])

In [38]:
half = len(bins) // 2
super_bins = torch.cat([bins[1:half] - 1,  bins,bins[half:-1] + 1])
bins_idx = torch.arange(len(bins))
bins_idx[-1] = 0
super_bins_idx = torch.cat([bins_idx[1:half],  bins_idx,bins_idx[half:-1]])

In [39]:
bins_idx

tensor([0, 1, 2, 0])

In [71]:
a = torch.stack(torch.meshgrid([bins_idx[:-1], bins_idx[:-1], bins_idx[:-1]]), dim=-1).reshape(-1, 3)

In [66]:
c = torch.arange(3*3*3).reshape(3,3,3)

In [72]:
c[a[:,0], a[:,1], a[:,2]]

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26])

In [45]:
b = torch.stack(torch.meshgrid([super_bins_idx, super_bins_idx, super_bins_idx]), dim=-1).reshape(-1, 3)

In [68]:
c[b[:,0], b[:,1], b[:,2]]

tensor([13, 12, 13, 14, 12, 14, 10,  9, 10, 11,  9, 11, 13, 12, 13, 14, 12, 14,
        16, 15, 16, 17, 15, 17, 10,  9, 10, 11,  9, 11, 16, 15, 16, 17, 15, 17,
         4,  3,  4,  5,  3,  5,  1,  0,  1,  2,  0,  2,  4,  3,  4,  5,  3,  5,
         7,  6,  7,  8,  6,  8,  1,  0,  1,  2,  0,  2,  7,  6,  7,  8,  6,  8,
        13, 12, 13, 14, 12, 14, 10,  9, 10, 11,  9, 11, 13, 12, 13, 14, 12, 14,
        16, 15, 16, 17, 15, 17, 10,  9, 10, 11,  9, 11, 16, 15, 16, 17, 15, 17,
        22, 21, 22, 23, 21, 23, 19, 18, 19, 20, 18, 20, 22, 21, 22, 23, 21, 23,
        25, 24, 25, 26, 24, 26, 19, 18, 19, 20, 18, 20, 25, 24, 25, 26, 24, 26,
         4,  3,  4,  5,  3,  5,  1,  0,  1,  2,  0,  2,  4,  3,  4,  5,  3,  5,
         7,  6,  7,  8,  6,  8,  1,  0,  1,  2,  0,  2,  7,  6,  7,  8,  6,  8,
        22, 21, 22, 23, 21, 23, 19, 18, 19, 20, 18, 20, 22, 21, 22, 23, 21, 23,
        25, 24, 25, 26, 24, 26, 19, 18, 19, 20, 18, 20, 25, 24, 25, 26, 24, 26])

In [ ]:
b[0]

In [40]:
super_bins_idx

tensor([1, 0, 1, 2, 0, 2])

In [28]:
super_bins

tensor([-0.6667,  0.0000,  0.3333,  0.6667,  1.0000,  1.6667])

In [29]:
torch.meshgrid([super_bins, super_bins, super_bins])

/home/holywater2/.conda/envs/infGCN/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


(tensor([[[-0.6667, -0.6667, -0.6667, -0.6667, -0.6667, -0.6667],
          [-0.6667, -0.6667, -0.6667, -0.6667, -0.6667, -0.6667],
          [-0.6667, -0.6667, -0.6667, -0.6667, -0.6667, -0.6667],
          [-0.6667, -0.6667, -0.6667, -0.6667, -0.6667, -0.6667],
          [-0.6667, -0.6667, -0.6667, -0.6667, -0.6667, -0.6667],
          [-0.6667, -0.6667, -0.6667, -0.6667, -0.6667, -0.6667]],
 
         [[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],
 
         [[ 0.3333,  0.3333,  0.3333,  0.3333,  0.3333,  0.3333],
          [ 0.3333,  0.3333,  0.3333,  0.3333,  0.3333,  0.3333],
          [ 0.3333,  0.3333,  0.3333,  0.3333,  0.3333,  0.3333],
    

In [31]:
torch.meshgrid([bins, bins, bins])[0]

tensor([[[0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.3333, 0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333, 0.3333]],

        [[0.6667, 0.6667, 0.6667, 0.6667],
         [0.6667, 0.6667, 0.6667, 0.6667],
         [0.6667, 0.6667, 0.6667, 0.6667],
         [0.6667, 0.6667, 0.6667, 0.6667]],

        [[1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000]]])

In [24]:
torch.stack([i*c[0] + j*c[1] + k*c[2] for i in [-1,0,1] for j in [-1,0,1] for k in [-1,0,1]])

tensor([[-9.0198, -9.0198, -9.0198],
        [-9.0198, -9.0198,  0.0000],
        [-9.0198, -9.0198,  9.0198],
        [-9.0198,  0.0000, -9.0198],
        [-9.0198,  0.0000,  0.0000],
        [-9.0198,  0.0000,  9.0198],
        [-9.0198,  9.0198, -9.0198],
        [-9.0198,  9.0198,  0.0000],
        [-9.0198,  9.0198,  9.0198],
        [ 0.0000, -9.0198, -9.0198],
        [ 0.0000, -9.0198,  0.0000],
        [ 0.0000, -9.0198,  9.0198],
        [ 0.0000,  0.0000, -9.0198],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  9.0198],
        [ 0.0000,  9.0198, -9.0198],
        [ 0.0000,  9.0198,  0.0000],
        [ 0.0000,  9.0198,  9.0198],
        [ 9.0198, -9.0198, -9.0198],
        [ 9.0198, -9.0198,  0.0000],
        [ 9.0198, -9.0198,  9.0198],
        [ 9.0198,  0.0000, -9.0198],
        [ 9.0198,  0.0000,  0.0000],
        [ 9.0198,  0.0000,  9.0198],
        [ 9.0198,  9.0198, -9.0198],
        [ 9.0198,  9.0198,  0.0000],
        [ 9.0198,  9.0198,  9.0198]])

In [ ]:
        atom_coord[batch==batch_idx] + torch.stack([i*cell[batch_idx][0] + j*cell[batch_idx][1] + k*cell[batch_idx][2] for i in [-1,0,1] for j in [-1,0,1] for k in [-1,0,1]],dim=0)


In [15]:
bins = torch.linspace(0, 1, 2+1)[:-1]

In [16]:
mesh = torch.meshgrid([bins, bins, bins])

In [17]:
mesh = torch.stack(mesh, dim=-1)

In [28]:
mesh_flat = mesh.reshape(-1, 3)

In [21]:
import grispy as gsp

In [24]:
from torch_geometric.nn import radius_graph, radius

In [126]:
cellb = torch.rand(2,3,3)
cellb = torch.tensor([[[1,0,0],[0,1,0],[0,0,1]]], dtype=torch.float)
cell_dir = torch.tensor([[i,j,k] for i in range(-1, 2) for j in range(-1, 2) for k in range(-1, 2)], dtype=torch.float)

In [127]:
cell_dir[0]

tensor([-1., -1., -1.])

In [128]:
cellb[0]

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [131]:
# (1)
cell_exp = torch.einsum("xj,bji->bxi", cell_dir, cellb)
cell_exp

tensor([[[-1., -1., -1.],
         [-1., -1.,  0.],
         [-1., -1.,  1.],
         [-1.,  0., -1.],
         [-1.,  0.,  0.],
         [-1.,  0.,  1.],
         [-1.,  1., -1.],
         [-1.,  1.,  0.],
         [-1.,  1.,  1.],
         [ 0., -1., -1.],
         [ 0., -1.,  0.],
         [ 0., -1.,  1.],
         [ 0.,  0., -1.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  1.],
         [ 0.,  1., -1.],
         [ 0.,  1.,  0.],
         [ 0.,  1.,  1.],
         [ 1., -1., -1.],
         [ 1., -1.,  0.],
         [ 1., -1.,  1.],
         [ 1.,  0., -1.],
         [ 1.,  0.,  0.],
         [ 1.,  0.,  1.],
         [ 1.,  1., -1.],
         [ 1.,  1.,  0.],
         [ 1.,  1.,  1.]]])

In [135]:
cell_exp.shape

torch.Size([1, 27, 3])

In [134]:
point = torch.randn(2,3)

In [142]:
pp = point.unsqueeze(1) + cell_exp

In [145]:
pp.flatten(0,1).shape

torch.Size([54, 3])

In [138]:
bb = torch.arange(3)

In [141]:
bb.repeat_interleave(27)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2])

In [115]:
cellb[0]

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [67]:
mesh_flat_idx = torch.tensor([i for i in range(mesh_flat.shape[0])], dtype=torch.long)

In [68]:
mesh_flat_idx

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [69]:
mesh_cell = []
mesh_cell_idx = []
for d in cell_dir:
    mesh_cell.append(mesh_flat + cell@d)
    mesh_cell_idx.append(mesh_flat_idx)

In [70]:
mesh_cell = torch.cat(mesh_cell, dim=0)
mesh_cell_idx = torch.cat(mesh_cell_idx, dim=0)

In [54]:
mesh_cell

tensor([[-1.0000, -1.0000, -1.0000],
        [-1.0000, -1.0000, -0.5000],
        [-1.0000, -0.5000, -1.0000],
        [-1.0000, -0.5000, -0.5000],
        [-0.5000, -1.0000, -1.0000],
        [-0.5000, -1.0000, -0.5000],
        [-0.5000, -0.5000, -1.0000],
        [-0.5000, -0.5000, -0.5000],
        [-1.0000, -1.0000,  0.0000],
        [-1.0000, -1.0000,  0.5000],
        [-1.0000, -0.5000,  0.0000],
        [-1.0000, -0.5000,  0.5000],
        [-0.5000, -1.0000,  0.0000],
        [-0.5000, -1.0000,  0.5000],
        [-0.5000, -0.5000,  0.0000],
        [-0.5000, -0.5000,  0.5000],
        [-1.0000, -1.0000,  1.0000],
        [-1.0000, -1.0000,  1.5000],
        [-1.0000, -0.5000,  1.0000],
        [-1.0000, -0.5000,  1.5000],
        [-0.5000, -1.0000,  1.0000],
        [-0.5000, -1.0000,  1.5000],
        [-0.5000, -0.5000,  1.0000],
        [-0.5000, -0.5000,  1.5000],
        [-1.0000,  0.0000, -1.0000],
        [-1.0000,  0.0000, -0.5000],
        [-1.0000,  0.5000, -1.0000],
 

In [72]:
mesh_cell_idx[b]

tensor([0, 1, 2, 3, 0, 1, 4, 5, 0, 2, 4, 6, 0, 1, 2, 4, 0, 1, 3, 5, 0, 2, 3, 6,
        1, 2, 3, 7, 0, 4, 5, 6, 1, 4, 5, 7, 2, 4, 6, 7, 3, 5, 6, 7, 1, 3, 5, 7,
        2, 3, 6, 7, 4, 5, 6, 7])

In [ ]:
mesh_cell_expand = 

In [55]:
a,b = radius(mesh_flat, mesh_cell, 0.6)

In [56]:
a,b

(tensor([ 36,  37,  38,  39,  82,  83,  86,  87,  97,  99, 101, 103, 104, 104,
         104, 104, 105, 105, 105, 105, 106, 106, 106, 106, 107, 107, 107, 107,
         108, 108, 108, 108, 109, 109, 109, 109, 110, 110, 110, 110, 111, 111,
         111, 111, 112, 114, 116, 118, 128, 129, 132, 133, 176, 177, 178, 179]),
 tensor([0, 1, 2, 3, 0, 1, 4, 5, 0, 2, 4, 6, 0, 1, 2, 4, 0, 1, 3, 5, 0, 2, 3, 6,
         1, 2, 3, 7, 0, 4, 5, 6, 1, 4, 5, 7, 2, 4, 6, 7, 3, 5, 6, 7, 1, 3, 5, 7,
         2, 3, 6, 7, 4, 5, 6, 7]))

In [59]:
edge_vec = mesh_flat[b]-mesh_cell[a]

In [62]:
torch.norm(edge_vec,dim=-1)

tensor([0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
        0.5000, 0.5000, 0.5000, 0.0000, 0.5000, 0.5000, 0.5000, 0.5000, 0.0000,
        0.5000, 0.5000, 0.5000, 0.0000, 0.5000, 0.5000, 0.5000, 0.5000, 0.0000,
        0.5000, 0.5000, 0.0000, 0.5000, 0.5000, 0.5000, 0.5000, 0.0000, 0.5000,
        0.5000, 0.5000, 0.0000, 0.5000, 0.5000, 0.5000, 0.5000, 0.0000, 0.5000,
        0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000,
        0.5000, 0.5000])