In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import pickle
import torch
import sys
import os
sys.path.append("../")
import time


/compuworks/anaconda3/envs/infGCN/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# batch_data = pickle.load(open('batch_data_train.pkl', 'rb'))
batch_data = pickle.load(open('mp_batch_data_for_unit_test.pkl', 'rb'))
g, densities, grid_coord, infos = batch_data
batch_data = {
    'atom_types': g.x,
    'atom_coord': g.pos,
    'grid': grid_coord,
    'batch': g.batch,
    'targets': densities,
    'infos': infos
}

In [4]:
for i, info in enumerate(batch_data["infos"]):
    print(f"{i}: {info['file_name']}")

0: mp-979413.chgcar
1: mp-677095.chgcar
2: mp-30510.chgcar
3: mp-1219846.chgcar
4: mp-974432.chgcar
5: mp-1212052.chgcar
6: mp-1039794.chgcar
7: mp-567499.chgcar
8: mp-1047437.chgcar
9: mp-972202.chgcar
10: mp-622018.chgcar
11: mp-1185464.chgcar
12: mp-1209644.chgcar
13: mp-1038594.chgcar
14: mp-1180386.chgcar
15: mp-1209820.chgcar
16: mp-1414188.chgcar
17: mp-5919.chgcar
18: mp-1216550.chgcar
19: mp-10287.chgcar
20: mp-22383.chgcar
21: mp-1218815.chgcar
22: mp-752420.chgcar
23: mp-1186512.chgcar
24: mp-1222421.chgcar
25: mp-1228343.chgcar
26: mp-1226874.chgcar
27: mp-1135.chgcar
28: mp-1025119.chgcar
29: mp-1222993.chgcar
30: mp-20737.chgcar
31: mp-1188110.chgcar


In [5]:
# we will use 12th file, SmIn2Cu9, Site 24, Tetrganoal

In [6]:
batch_data.keys()

dict_keys(['atom_types', 'atom_coord', 'grid', 'batch', 'targets', 'infos'])

In [7]:
atom_types = batch_data["atom_types"]
atom_coord = batch_data["atom_coord"]
grid = batch_data["grid"]
batch = batch_data["batch"]
infos = batch_data["infos"]
targets = batch_data["targets"]

In [8]:
# Refine to 12th file
idx = 12
atom_types = atom_types[batch==idx]
atom_coord = atom_coord[batch==idx]
infos = [infos[idx]]
batch = batch[batch==idx]
batch[batch==idx] = 0
target = targets[idx].unsqueeze(0)
grid = grid[idx].unsqueeze(0)

In [9]:
# test_cell = torch.tensor([[1,0,0.1], [0,1,0], [0.1,0,1]], dtype=torch.float32)
# test_coord = torch.tensor([[0.25, 0.25, 0.25],[0.5,0.25,0.25]], dtype=torch.float32)
# test_batch = torch.tensor([0,0], dtype=torch.int64)
# test_type = torch.tensor([1,2], dtype=torch.int64)

In [10]:
def make_supercell(atom_types, atom_coord, batch, infos, supercell_idx = [1,1,1]):
    cell = infos[0]["cell"]
    supercell_idx = torch.tensor(supercell_idx)
    supercell = torch.einsum("i,ij->ij", supercell_idx.float().to(cell.device),cell)
    super_coords = []
    super_types = []
    for i in range(supercell_idx[0]):
        for j in range(supercell_idx[1]):
            for k in range(supercell_idx[2]):
                super_coords.append(atom_coord + i*cell[0] + j*cell[1] + k*cell[2])
                super_types.append(atom_types)
    
    super_types = torch.cat(super_types, dim=0).to(atom_types.device)
    super_coords = torch.cat(super_coords, dim=0).to(atom_coord.device)
    super_batch = torch.zeros_like(super_types).to(atom_types.device)
    super_infos = infos[0].copy()
    super_infos["cell"] = supercell
    print("number of atoms",len(super_types))
    print("original cell\n", cell)
    print("supercell\n", supercell)
    print("supercell_idx\n", supercell_idx)
    return super_types, super_coords, super_batch, [super_infos]

In [11]:
from source.models.GPWNO_test import GPWNO
from source.baseline.infgcn import InfGCN

In [4]:
GPWNO_qm9 = GPWNO(
    n_atom_type=5,
    num_radial=16,
    num_spherical=4,
    radial_embed_size=64,
    radial_hidden_size=128,
    num_radial_layer=2,
    num_gcn_layer=2,
    cutoff=3.0,
    is_fc=False,
    gauss_start=0.5,
    gauss_end=5.,
    residual=True,
    pbc=False,
    activation="norm",
    num_fourier=40,
    num_fourier_time=12,
    width=16,
    fourier_mode=0,
    padding=4,
    use_max_cell=True,
    equivariant_frame=True,
    probe_cutoff=1.5,
    grid_cutoff=0.75,
    normalize=True,
    using_ff=True,
    model_sharing=False,
    num_infgcn_layer=3,
    use_detach=False,
    num_spherical_RNO=4,
    scalar_mask=True,
    mask_cutoff=3.0,
    input_infgcn=False,
    output_positive=False,
    atom_info="/home/holywater2/crystal/GPWNO/atom_info/qm9_atom_info.json",
    input_dist=False,
    atomic_gauss_dist=False
).cuda()

NameError: name 'GPWNO' is not defined

In [13]:
# model2 = InfGCN(
#     n_atom_type=85,
#     num_radial=16,
#     num_spherical=7,
#     radial_embed_size=64,
#     radial_hidden_size=128,
#     num_radial_layer=2,
#     num_gcn_layer=3,
#     cutoff=5.0,
#     is_fc=False,
#     gauss_start=0.5,
#     gauss_end=5.,
#     residual=False,
#     pbc=True,
#     activation="norm",    
# ).cuda()

In [14]:
# model3 = InfGCN(
#     n_atom_type=85,
#     num_radial=16,
#     num_spherical=3,
#     radial_embed_size=64,
#     radial_hidden_size=128,
#     num_radial_layer=2,
#     num_gcn_layer=3,
#     cutoff=5.0,
#     is_fc=False,
#     gauss_start=0.5,
#     gauss_end=5.,
#     residual=False,
#     pbc=True,
#     activation="norm",    
# ).cuda()

In [15]:
def time_stats(model, atom_types, atom_coord, grid, batch,infos, supercell_idx =[1,1,1],num_iter=100,model_type="GPWNO"):
    at, ac, b, ifs = make_supercell(atom_types, atom_coord, batch, infos, supercell_idx)
    g = grid
    t = 0
    probe_degree = 0
    start_time = time.time()
    with torch.no_grad():
        for i in range(num_iter):
            dd = model.forward(at, ac, g, b, ifs)
            if type == "GPWNO":
                t += dd["time"]
            
    end_time = time.time()
    runtime = end_time - start_time
    print("total runtime     :",runtime, runtime/num_iter)
    if model_type == "GPWNO":
        print("runtime w/o radius:",runtime - t, (runtime - t)/num_iter)
        print("probe degree      :",dd["avg_probe_degree"])
        print("sample degree     :",dd["avg_sample_degree"])
        print("probe exist rate  :",dd["avg_probe_exist_rate"])
        print("probe exist degr  :",dd["avg_probe_exist_degree"])
    del at, ac, b, ifs, dd

In [16]:
from torch_geometric.data.batch import DataBatch

def time_stats_train(model, atom_types, atom_coord, grid, batch,infos, target, supercell_idx =[1,1,1],num_iter=100,model_type="GPWNO"):
    print("mode: train")
    at, ac, b, ifs = make_supercell(atom_types, atom_coord, batch, infos, supercell_idx)
    g = grid
    t = 0
    probe_degree = 0
    databatch = DataBatch(x=at, pos=ac, batch=b)
    # print(databatch)
    start_time = time.time()
    for i in range(num_iter):
        dd = model.training_step([databatch,target,g,ifs],0)
        if type == "GPWNO":
            t += dd["time"]
            
    end_time = time.time()
    runtime = end_time - start_time
    print("total runtime     :",runtime, runtime/num_iter)
    del at, ac, b, ifs, dd
    return len(atom_types), runtime

In [17]:
time_stats_train(model1, atom_types, atom_coord, grid, batch, infos, target, supercell_idx = [1,1,1],num_iter=1)

mode: train
number of atoms 24
original cell
 tensor([[0.0000, 0.0000, 5.0236],
        [8.4651, 0.0000, 0.0000],
        [0.0000, 8.4651, 0.0000]], device='cuda:0')
supercell
 tensor([[0.0000, 0.0000, 5.0236],
        [8.4651, 0.0000, 0.0000],
        [0.0000, 8.4651, 0.0000]], device='cuda:0')
supercell_idx
 tensor([1, 1, 1])


/compuworks/anaconda3/envs/infGCN/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


total runtime     : 9.758800029754639 9.758800029754639


/compuworks/anaconda3/envs/infGCN/lib/python3.9/site-packages/pytorch_lightning/core/module.py:420: You are trying to `self.log()` but the `self.trainer` reference is not registered on the model yet. This is most likely because the model hasn't been passed to the `Trainer`


(24, 9.758800029754639)